#!/bin/sh
echo "Choose version bump: [p]atch or [m]inor? (default: skip)"
exec </dev/tty
read BUMP_CHOICE

case "$BUMP_CHOICE" in
m | M) BUMP_TYPE="minor" ;;
p | P) BUMP_TYPE="patch" ;;
*)
  echo "No version bump performed."
  exit 0
  ;;
esac

echo "Performing a $BUMP_TYPE version bump."
npm version "$BUMP_TYPE" --git-tag-version=false
if [ $? -ne 0 ]; then
  echo "npm version command failed. Aborting."
  exit 1
fi

git add package.json package-lock.json
